### ISSUE TITLE
ValueError: The given no-data value (256.0) is out range for data type uint8.

### ISSUE THREAD

**Issue by Weixing-Zhang** [SMByC/Coregistration-Qgis-processing#6] opened 2022-03-07 17:52 UTC
Hi,

I was testing the tool for global registration. I received the following error.

```
File "C:\Users\home\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Coregistration\extlibs_windows\geoarray\baseclasses.py", line 162, in _validate_nodataVal
raise ValueError("The given no-data value (%s) is out range for data type %s."
ValueError: The given no-data value (256.0) is out range for data type uint8.
```

Both the reference and target images are within the range of 0 to 255 (see below). I am not sure what causes the error. Any insights? Thank you for your help.

**Target image** 
Number	Band	No-Data	Min	Max
1	Band 1	n/a	21.0000000000	255.0000000000
2	Band 2	n/a	12.0000000000	255.0000000000
3	Band 3	n/a	1.0000000000	255.0000000000

**Reference image**
Number	Band	No-Data	Min	Max
1	Band 1	n/a	0.0000000000	253.0000000000
2	Band 2	n/a	8.0000000000	253.0000000000
3	Band 3	n/a	0.0000000000	250.0000000000

**Comment by XavierCLL** [comment] 2022-03-07 19:53
Hi @Weixing-Zhang 

The error shows a conflict between the nodata value set in the layers and their data type. Reset or unset the nodata value to both layers and try again.

**Comment by Weixing-Zhang** [comment] 2022-03-08 01:10
Hi @XavierCLL 

Thank you for your help. I ended by making it work by reseting nodata value to zero. I noticed that the conda installation instructions do not really work on Mac computers with Apple silicon. I perhaps should create a new issue for that?

**Comment by XavierCLL** [comment] 2022-03-08 01:33
Hi @Weixing-Zhang glad to know you could run that in Windows.

For the ARM architecture (e.g. Mac silicon) I'm not sure that all the libraries and apps are ready for that, no idea if the problem is due to Arosics or Qgis packages in that architecture in the conda repository, maybe @[danschef](https://github.com/danschef) knows more about it.

**Comment by danschef** [comment] 2022-03-08 09:56
So far as I know, `conda create -n envname -c conda-forge qgis 'arosics>=1.3.0' also works on Mac`. This should install QGIS 3.18 and the latest version of AROSICS into the same environment.

**Comment by XavierCLL** [comment] 2022-03-08 19:01
Thanks Daniel! you can continue the discussion about Arosics for ARM here https://git.gfz-potsdam.de/danschef/arosics/-/issues/72, closing this.

**Closed by XavierCLL** 2022-03-08 19:01 UTC
