### ISSUE TITLE
Python error - installing Co-registration plugin in QGIS - Ubuntu

### ISSUE THREAD

**Issue by tazrart** [SMByC/Coregistration-Qgis-processing#5] opened 2022-02-02 15:33 UTC
Dear all,

Following the pixel shift that I identified between the "Prisma" L2D hyperspectral image and the Sentinel 2 L2A images, the Enmap-box plugin maintainers advise me to use your Co-registration plugin to make the corrections (see the issue below):

https://bitbucket.org/hu-geomatics/enmap-box/issues/965/pixel-shift-between-prisma-l2d-and

So I installed this plugin via QGIS 3.22 on Ubuntu 20, then prepared the reference image and target image as follows:

- First, I prepared the reference image, I recorded a single band of Sentinel 2 and then I cut it according to the Prisma image frame. So both Sentinel 2 and Prisma images have the same extent:

![overlap](https://user-images.githubusercontent.com/36005324/152184138-5d5d5e63-a498-4214-8572-21fe992670fe.png)

- I did a first test with the "Automated local co-registration" module of this plugin:

- The reference image: one band of the sentinel image (already cut with the same Prisma frame).
The traget image: prisma L2D image
The other settings, I didn't change anything, I kept it by default.

![local_coregistration_window](https://user-images.githubusercontent.com/36005324/152184408-af6dd9c1-dc58-4307-9513-0da3592b0746.png)

- Unfortunately, I have the following errors:

![error](https://user-images.githubusercontent.com/36005324/152184428-bcd29ed0-2b96-4b1a-abd6-4810d6e48313.png)

- Subsequently, I followed the instructions detailed in your site to install this plugin under Ubuntu using a single environment under Conda:
https://github.com/SMByC/Coregistration-Qgis-processing

#installation

Here are the steps I did:

First I installed anaconda , then I applied these command lines in terminal:

> conda create --name qgis_arosics
> conda activate qgis_arosics
> conda install qgis --channel conda-forge
> conda install -c conda-forge arosics

The version of QGIS installed under conda is 3.18:

![version_qgis_conda](https://user-images.githubusercontent.com/36005324/152184663-935e55c5-9e47-468a-b7b3-35479e50e8e4.png)

I subsequently installed the Co-registration plugin but once launched the "Automated global co-registration" module, there is a python error that appears:

![python_message](https://user-images.githubusercontent.com/36005324/152184755-5ec122a7-ab54-4063-bdab-6646e1e4d16a.png)
![error_coregistration_conda](https://user-images.githubusercontent.com/36005324/152184798-2b3b2c96-fbb5-44b9-85e9-60a6fb8bb7cd.png)

and the treatment process does not give any results??

![processing](https://user-images.githubusercontent.com/36005324/152184828-0390c9df-6440-45b8-b767-bbe40a54830f.png)

It is possible confusion between the different versions of python installed on computer, do you have a solution, please, for this type of error ?!!

Thank you in advance for your answer ?

Best regards

**Comment by XavierCLL** [comment] 2022-02-02 19:11
Hi @tazrart 

In Linux is easier (IMO) trying first install Arosics locally with this command:

`pip install arosics --user`

And try to use the Qgis of the system, and first try run the Global coregistration, the Local coregistration takes more time to process.

The error with the Qgis using anaconda is not related to the plugin, and it is weird that the plugin either does not work or the settings to run Local coregistration are hard to process and it needs more time to process (try first the Global instead). Open the python console before running the plugin to check the process or any error.

Regards

**Comment by danschef** [comment] 2022-02-02 20:24
`conda install -c conda-forge arosics` should install all dependencies needed for arosics. To validate that the installation worked, open a Python console in QGIS and `import arosics` there. If that works, we can proceed. However, the `TypeError` as shown in your screenshot looks like the issue is somwhere in the code of the plugin.

**Comment by tazrart** [comment] 2022-02-04 15:35
Thank you  @XavierCLL and @danschef  for your answers. 

I. QGIS 3.22 - system:

Indeed, I reinstalled QGIS 3.22 in the system and then I installed the Coregistration plugin, I ran the "Automated Global Co-registration" plugin but I have this error:

![coregistration_error](https://user-images.githubusercontent.com/36005324/152555734-b8c3cced-4fad-4892-8af7-a9fbc64e57af.png)


I imported arosics via QGIS python console, below are the errors:
![import_arosics](https://user-images.githubusercontent.com/36005324/152555918-ad8d1b42-88fa-41d9-8819-f3f7263a294d.png)

![import_arosics1](https://user-images.githubusercontent.com/36005324/152556020-27ac5df8-3e9a-4a3e-8d05-cef4022d68da.png)

![import_arosics2](https://user-images.githubusercontent.com/36005324/152556079-baa34f35-c223-431f-9416-fc2b010e123d.png)

Subsequently, I uninstalled the "Co-registration" plugin and tried to install "arosics" via the terminal but apparently there is a problem with the "Proj" package, the installed version is 7.2.1 but cartopy package requires version 8.0.0

![arosics_installation](https://user-images.githubusercontent.com/36005324/152556289-8512f310-e50f-412a-ade2-986d7da6b1da.png)

So I tried to update this package but I have this as results? What to do in this case :

![proj_installation](https://user-images.githubusercontent.com/36005324/152556361-e61775f7-8739-40ae-bc25-4e0f2e44064d.png)

II. QGIS 3.18 conda environment:

For QGIS installed under Conda, I imported "arosics" in the QGIS python console and I still have the same error quoted in my first issue:
![import_arosics_error](https://user-images.githubusercontent.com/36005324/152556477-0c5ccf2a-fb8b-4b4f-bad2-f3900ccc4863.png)
![erreur python](https://user-images.githubusercontent.com/36005324/152556542-37935d04-3d4f-4cae-81cc-d9f1bec85620.png)

Sorry for all these errors, hoping that there will be a solution!!

Thanks again,

Best regards ,

**Comment by danschef** [comment] 2022-02-04 16:19
@tazrart Installing arosics from pip will most likely not work because some packages do not compile well on every platform. That´s why I strongly recommend to install arosics with conda as you get pre-compiled packages there. This is also documented in the [installation instructions of AROSICS](https://danschef.git-pages.gfz-potsdam.de/arosics/doc/installation.html). To make arosics work within qgis, I therefore recommend to install arosics and qgis into a single conda environment:

`conda create -n arosics_env -c conda-forge qgis arosics`

To speed up the installation, I recommend to use [Mambaforge](Mambaforge) and or to install the mamba package into the base environment of conda (`conda install -c conda-forge -n base mamba`). Instead of the above command, you can then run:

`mamba create -n arosics_env -c conda-forge qgis arosics`

This should be much faster. Also make sure that your conda base environment is up-to-date before creating the conda environment as an old conda package resolver might affect the installation (`conda update -c conda-forge -n base --all`).

The `arosics_env` environment will contain QGIS 3.18 (newer versions of QGIS are currently not available from conda). Install the plugin via the plugin manager and validate that arosics is importable on a Python console within QGIS. If that works and you still get an error when running the co-registration via the plugin, then post it here. However, you should then still be able to run the co-registration without the plugin as demonstrated in the [documentation of arosics](https://danschef.git-pages.gfz-potsdam.de/arosics/doc/).

**Comment by XavierCLL** [comment] 2024-02-03 15:46
I'm closing this (old) bug because since the latest version v23.11 or higher the plugin automatically installs all the libraries that need to work in any OS.

**Closed by XavierCLL** 2024-02-03 15:46 UTC
