### ISSUE TITLE
About windows QGIS plugins co-registration errors

### ISSUE THREAD

**Issue by xiaoenli4816** [SMByC/Coregistration-Qgis-processing#10] opened 2023-11-01 13:08 UTC
Error loading Arosics, this plugin requires additional Python packages to work. For Windows users, download and reinstall the plugin with this zip all-in-one with all the libs and dependencies. Read the install instructions here:

https://github.com/SMByC/Coregistration-Qgis-processing#installation

**Comment by XavierCLL** [comment] 2023-11-01 20:22
@xiaoenli4816 

Follow the error message, manually install the plugin using the zip `Coregistration_all_in_one_win.zip` from https://github.com/SMByC/Coregistration-Qgis-processing#windows

**Comment by xiaoenli4816** [comment] 2023-11-02 00:34
@XavierCLL I uninstalled the plugin that was reporting the error and installed it as per the above tutorial, and restarted QGIS, and I still get the above error! (Error loading Arosics, this plugin requires additional Python packages to work. For Windows users, download and reinstall the plugin with this zip all-in-one with all the libs and dependencies. Read the install instructions here:https://github.com/SMByC/Coregistration-Qgis-processing#installation)

**Comment by XavierCLL** [comment] 2023-11-02 00:42
@xiaoenli4816 ok, so it seems an issue with the external libraries that the plugin needs to work, could you please tell me the Qgis and Python versions in Qgis (in Qgis, Help > About), is your Windows 64bits?

**Comment by xiaoenli4816** [comment] 2023-11-02 00:48
Hello, about QGIS
![未命名1698885986](https://github.com/SMByC/Coregistration-Qgis-processing/assets/68621896/530be200-2e28-4fb0-a39d-d3bf9ff3e750), Yes, my computer is Windows 64bits.

**Comment by XavierCLL** [comment] 2023-11-02 00:56
Thanks for your report, I'm going to check this problem, and when I have a version to check, I'll write you, stay tuned

**Comment by XavierCLL** [comment] 2023-11-04 05:35
Hi @xiaoenli4816 

Could you please test with this zip https://github.com/SMByC/Coregistration-Qgis-processing/releases/download/23.11/Coregistration.zip

Also, I recommended updating your Qgis version, I found some issues related to some old Qgis version

Let me know if it works for you, 
Xavier

**Comment by xiaoenli4816** [comment] 2023-11-04 09:16
Hello, it  still have some wrong, 

![error](https://github.com/SMByC/Coregistration-Qgis-processing/assets/68621896/e08bbfca-09cd-49e3-891a-b36d26247a58)
[error.txt](https://github.com/SMByC/Coregistration-Qgis-processing/files/13256218/error.txt)
![error1](https://github.com/SMByC/Coregistration-Qgis-processing/assets/68621896/4310b495-d7bf-428e-a896-ef024d9bc261)

**Comment by XavierCLL** [comment] 2023-11-04 18:46
Could you please open the python console there in Qgis and check the numpy version with:

```
import numpy
numpy.version.version
```

**Comment by XavierCLL** [comment] 2023-11-04 23:29
Hi @xiaoenli4816 

Mismaching with the nupy version installed, I just updated the external libs. Please close Qgis and remove the plugin directory, in your case is in: `C:\Users/DELL/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Coregistration`, and install it again usgin the same zip I sent you in the previous post and check if it is working

Thanks for your tests

**Comment by xiaoenli4816** [comment] 2023-11-05 01:56
Hello, my numpy version is '1.22.0'. there is still have same wrong issue, QGIS version: 3.32.3-Lima
QGIS code revision: 67d46100b5
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)
Algorithm started at: 2023-11-05T09:55:07
Algorithm 'Automated local Co-Registration' starting…
Input parameters:
{ 'ALIGN_GRIDS' : True, 'GRID_RES' : 20, 'IMG_REF' : 'I://……//DSM/202309_clip.tif', 'MATCH_GSD' : True, 'MAX_SHIFT' : 5, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RESAMPLING' : 2, 'WINDOW_SIZE' : 20 }


Error loading Arosics, this plugin requires additional Python packages to work. For Windows users, download and reinstall the plugin with this zip all-in-one with all the libs and dependencies. Read the install instructions here:

**Comment by XavierCLL** [comment] 2023-11-05 03:22
That was a silly code error by my part, please download this again https://github.com/SMByC/Coregistration-Qgis-processing/releases/download/23.11/Coregistration.zip and re-install it.

**Comment by xiaoenli4816** [comment] 2023-11-05 04:11
There has same error, Is it the python environment/ influenced by other's libraries?

**Comment by XavierCLL** [comment] 2023-11-05 04:16
Maybe yes, I tested using a virtual machine with Windows, and it works fine. I recommend you uninstall all the Qgis versions and install just one. If the error persist, you can use Qgis from conda described [here](https://github.com/SMByC/Coregistration-Qgis-processing#alternative-installation) or use Arosics directly

**Comment by xiaoenli4816** [comment] 2023-11-05 04:18
Is it convenient/available? Can you take a look at it remotely?

**Comment by XavierCLL** [comment] 2023-11-05 05:52
You have an issue related to your Qgis installations, some libs or software related or even Windows. Do a full reinstallation of Qgis  would help. But I cannot do more here.

**Comment by XavierCLL** [comment] 2023-11-05 05:56
I'm going to close this because the problem is specific to installed user system and very surely not related to this plugin (not completely)

**Closed by XavierCLL** 2023-11-05 05:56 UTC

**Comment by xiaoenli4816** [comment] 2023-11-05 05:59
ok, thanks for your help, reply, remainder.
Best regrads,
